version: '3.0'

expectations:
  population_size: 1000

actions:

  create_matched_cases:
    run: >
      python:latest
        analysis/create_matched_cases.py
    outputs:
      highly_sensitive:
        cases: output/matched_cases_stp.csv

  generate_dataset:
    run: >
      databuilder:v0
        generate-dataset analysis/dataset_definition.py
        --output output/dataset.arrow
    needs:
      [create_matched_cases]
    outputs:
      highly_sensitive:
        cohort: output/dataset.arrow
